<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="26981" started-at="2019-10-30T00:29:14Z" finished-at="2019-10-30T00:29:41Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="26981" started-at="2019-10-30T00:29:14Z" finished-at="2019-10-30T00:29:41Z">
      <class name="TestNGSessions.LoginPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestNGSessions.LoginPageTest@ae45eb6]" name="setUp" is-config="true" duration-ms="8999" started-at="2019-10-29T20:29:14Z" finished-at="2019-10-29T20:29:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginTest()[pri:3, instance:TestNGSessions.LoginPageTest@ae45eb6]" name="loginTest" duration-ms="17063" started-at="2019-10-29T20:29:23Z" finished-at="2019-10-29T20:29:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	header text is not matched... expected [Sales Dashboard123] but found [Sales Dashboard],
	expected [Reports dashboard123] but found [Reports dashboard]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	header text is not matched... expected [Sales Dashboard123] but found [Sales Dashboard],
	expected [Reports dashboard123] but found [Reports dashboard]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at TestNGSessions.LoginPageTest.loginTest(LoginPageTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestNGSessions.LoginPageTest@ae45eb6]" name="tearDown" is-config="true" duration-ms="811" started-at="2019-10-29T20:29:40Z" finished-at="2019-10-29T20:29:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestNGSessions.LoginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
